### ISSUE TITLE
package is empty

### ISSUE THREAD

**Issue by vapniks** [ropensci/PostcodesioR#1]
After following your installation instructions and loading the library, no new functions are loaded.
```
> devtools::install_github("erzk/PostcodesioR")
> ls(2)
character(0)
```

**Comment by erykwalczak** [comment]
Thanks for pointing this out. Probably I haven't built and reloaded the package before pushing it to GH. I'll try to fix it ASAP.

**Comment by erykwalczak** [comment]
`@export` was missing from the functions so they were not added correctly to the NAMESPACE which meant that the functions were not loaded with the package. it's fixed now.

**Comment by vapniks** [comment]
Great, thanks.
