### ISSUE TITLE
codecov.io push suggestion/issue

### ISSUE THREAD

**Issue by layik** [ropensci/PostcodesioR#10]
Might want to check `ropensci/stats19` travis YML to send active pushes to [codecov.io](https://codecov.io/github/ropensci/PostcodesioR?branch=master). I can see the `covr` package check locally being `89.51%` would do with few more tests if need be.

Not urgent or necessary at all. Close it if you wish.

**Comment by erykwalczak** [comment]
I [updated](https://github.com/ropensci/PostcodesioR/commit/e707e6e35854128204343c1b023a873fac3098f4) `travis.yml` using the template from stats19:

Dependencies used in stats19 were not used in my yml file. It looks like I disconnected codecov from my package but running `covr::codecov(token = "TOKEN")` fixed the issue. Now the coverage is displayed correctly.
