### ISSUE TITLE
Error with CB1 postcodes

### ISSUE THREAD

**Issue by barobinson** [ropensci/PostcodesioR#12]
For example
`postcode_lookup("CB13AB")`
returns the error
`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0`
However http://api.postcodes.io/postcodes/cb13ab returns a valid result

**Comment by erykwalczak** [comment]
This looks like #11 
Are you using the CRAN version? If so, please switch to the dev version on GitHub. Changes to the CRAN version have not been accepted yet. Actually, it's probably time for me to check what is holding it back.
Thanks

**Comment by barobinson** [comment]
Thank you. Yes this was the same issue, and switching to the dev version fixed the problem.
