### ISSUE TITLE
Radius parameter not working in nearest_postcode

### ISSUE THREAD

**Issue by josho88** [ropensci/PostcodesioR#13]
Hi

I noticed the radius parameter was not having the desired effect in the nearest_postcode function. Possibly due to the extra ? in the query string below?

`
 r <- GET(paste0("https://api.postcodes.io/postcodes/",
                  postcode,
                  "/nearest",
                  "?limit=",
                  limit,
                  "?radius=",
                  radius))
  extract_results(r)
`

**Comment by erykwalczak** [comment]
Well spotted, thanks. I've raised an issue with the creator of the API: https://github.com/ideal-postcodes/postcodes.io/issues/666 
PostcodesioR is just a wrapper so it depends on the underlying API.
