### ISSUE TITLE
Help vignette for bulk_postcode_lookup is inaccurate 

### ISSUE THREAD

**Issue by dave-lovell** [ropensci/PostcodesioR#15]
The help vignette for `bulk_postcode_lookup()` states that argument `postcodes`  'Accepts a list of postcodes'. This is untrue - I've just spent 15 minutes working out that it accepts a list of length one, whose sole element is a character vector of postcodes. 

```
## This will work:
bulk_postcode_lookup( list( postcodes = c("PR3 0SG", "M45 6GN", "EX165BL")))

## This will not work:
bulk_postcode_lookup( list("PR3 0SG", "M45 6GN", "EX165BL"))
```

The documentation (with the exception of the examples) implies the latter is the correct syntax.

I'm not sure why the character vector needs to be wrapped in a list, but I'm treating this as a documentation error rather than a missing feature.

**Comment by erykwalczak** [comment]
Thanks for raising the issue. Will look into this over the weekend.

**Comment by erykwalczak** [comment]
Fixed https://github.com/ropensci/PostcodesioR/commit/0077c0a19062c82572b4129ecf4def6dca5416ad
