### ISSUE TITLE
Submit to CRAN?

### ISSUE THREAD

**Issue by sckott** [ropensci/PostcodesioR#3]
👋 Any plans to submit to CRAN?  Anything we can do to help?

**Comment by erykwalczak** [comment]
That's definitely the plan. I'm quite busy these days so it might need to wait. 
It would be helpful to know what needs improving in order to have the package accepted to CRAN.

**Comment by sckott** [comment]
- one rule about CRAN maintainers is they are not consistent, so they may or may not complain about certain things
- run your pkg against rhub with https://github.com/r-hub/rhub and against cran's windows testers with `devtools::check_win_devel()` and `devtools::check_win_release()` - which should bring up anything you may need to change

took a quick look, and i see a few things:

- Title in DESCRIPTION file: this should be each word capitalized. 
- Description in DESCRIPTION file: they'll probaably want postcodes.io as `<https://postcodes.io>` or whatever the full url is
- examples: think about your examples that make http requests, if they fail when running on CRAN, they'll treat it as a bug and make you resubmit
- tests: any tests that make http requests, for CRAN you may want to change the setup. some options are: 1) just run tests as normal, but if they ever fail, CRAN will make you fix and resubmit, 2) `testthat::skip_on_cran` so that tests run locally and on CI's, but not on CRAN, 3) mock tests, could use https://cran.r-project.org/web/packages/webmockr/ or https://cran.r-project.org/web/packages/vcr/

**Comment by erykwalczak** [comment]
Thanks for the suggestions. I've just submitted to CRAN.

**Comment by erykwalczak** [comment]
PostcodesioR is now on [CRAN](https://cran.r-project.org/web/packages/PostcodesioR/index.html).
