### ISSUE TITLE
Missing postcode

### ISSUE THREAD

**Issue by paulfwb** [ropensci/PostcodesioR#5]
I attempted a lookup using the list c("EC1Y8LX", "SW1X 7XL", "DE3 5LF", "DE3 9LR").
All were successful except for "DE3 5LF" for which a "Not Found (HTTP 404)" message was returned. I have since confirmed that "DE3 5LF" is a valid postcode.

Best regards,
Paul

**Comment by erykwalczak** [comment]
Hi Paul.
404 is what postcodes.io return. Running `terminated_postcode("DE3 5LF")` shows that this postcode was terminated in Dec 2001. ONS geography linked data also shows this postcode is obsolete. How did you confirm that it's a valid postcode?

**Comment by erykwalczak** [comment]
ONS lookup: http://statistics.data.gov.uk/atlas/search?search-term=DE3+5LF

**Comment by paulfwb** [comment]
Hi Eryk
I assume, given that “DE3 5LF” is obselete, this source is also out of date. https://www.doogal.co.uk/ShowMap.php?postcode=DE3%209LF <https://www.doogal.co.uk/ShowMap.php?postcode=DE3%209LF>
However, I have not yet found what the current version is.
It appears this change in the postcode mush be very recent.

See : https://www.rightmove.co.uk/house-prices/DE3/Tasman-Close.html <https://www.rightmove.co.uk/house-prices/DE3/Tasman-Close.html>

Best regards,
Paul

**Comment by erykwalczak** [comment]
The first postcode that you linked to (on doogal.co.uk) is DE3 **9**LF. The rightmove page is showing house prices in the DE3 **outcode** and DE3 **9**LF so different from what you initially reported (i.e. DE3 **5**LF).
