### ISSUE TITLE
Only centroids available as opendata?

### ISSUE THREAD

**Issue by paulb20** [ropensci/PostcodesioR#6]
As an Openstreetmap mapper, use of postcode datasets comes up frequently, and usually ends up with people saying there's a doubt about licence compatibility. The underlying Codepoint Open is OGL, which is fine for Openstreetmap ODBL and others, but this is only for centroids of postcode areas. The Postcode Address File remains closed. I guess for a lot of uses this isn't an issue, but as many postcode areas are really odd shapes, and in some cases heights - I used to live in a tower block with 3 postcodes comprising different floors, so identical centroids, there could be some use cases that are problematic.

**Comment by erykwalczak** [comment]
Only centroids are available in PostcodesioR. This package is just a wrapper so it provides only data that is available via the API. You might want to request new features from postcodes.io: https://github.com/ideal-postcodes/postcodes.io/
