### ISSUE TITLE
Is there a 100 bulk limit?

### ISSUE THREAD

**Issue by layik** [ropensci/PostcodesioR#8]
Awesome package to start with!

I discovered via using the package that there is a [100](https://github.com/ropensci/PostcodesioR/blob/6663061ffade6e654e69e3372322729aebba7dfd/R/postcode_query.R#L25) bulk lookup limit. Correct? If so, I am happy to contribute to make that clear rather than returning a `In extract_results(r) : Bad Request (HTTP 400).` error which lead me to sanity check my postcodes.

Thanks and hoping it is a valid "issue".

**Comment by erykwalczak** [comment]
Thanks for opening the issue. It is valid. I agree that the error message is not clear. I mentioned this limit in the function [documentation](https://github.com/ropensci/PostcodesioR/blob/master/man/bulk_postcode_lookup.Rd).
Feel free to send a PR. Also, bear in mind that the GitHub version is slightly ahead of CRAN so please use this version to make changes.

**Comment by layik** [comment]
OK, so digging further this is strictly from [postcodes.io](https://postcodes.io/docs) and hence the 400 error. Will send a tiny PR without fiddling too much with `bulk_postcode_lookup` function which would do with a little more but will keep it to the issue.

**Comment by erykwalczak** [comment]
Thanks. Fixed in PR #9
